import * as THREE from 'three';
import { OrbitControls } from './assets/OrbitControls.js';
import { RoomEnvironment } from './assets/RoomEnvironment.js';
const $=selector=>document.querySelector(selector);
const page=document.body.dataset.page;
const reducedQuery=matchMedia('(prefers-reduced-motion: reduce)');
let reduced=reducedQuery.matches;
let motionPaused=reduced;
const contact=$('#contact-dialog');
let contactTopic=page==='journey'?'Longevity Journey':'';
function openContact(topic=''){contactTopic=topic;$('#whatsapp-link').href='https://wa.me/523319045014?text='+encodeURIComponent('Hola Insiders, me gustaría conocer '+(topic||'sus servicios')+' y consultar una valoración.');contact.showModal();}
document.querySelectorAll('[data-contact]').forEach(button=>button.addEventListener('click',()=>openContact(button.dataset.topic||contactTopic)));
document.querySelectorAll('dialog').forEach(dialog=>{dialog.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',event=>{if(event.target!==dialog)return;const rect=dialog.getBoundingClientRect();if(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom)dialog.close();});});
$('#open-sources').addEventListener('click',()=>$('#sources-dialog').showModal());
const menu=$('#menu-toggle'),nav=$('#main-nav');
function closeMenu(){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Abrir menú');}
menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Cerrar menú':'Abrir menú');});
document.addEventListener('keydown',event=>{if(event.key==='Escape')closeMenu();});
nav.addEventListener('click',event=>{if(event.target.closest('a'))closeMenu();});
const pointer={x:0,y:0};
document.addEventListener('pointermove',event=>{if(reduced||event.pointerType==='touch')return;pointer.x=(event.clientX/innerWidth-.5)*2;pointer.y=(event.clientY/innerHeight-.5)*2;document.body.style.setProperty('--mouse-x',event.clientX+'px');document.body.style.setProperty('--mouse-y',event.clientY+'px');},{passive:true});
document.querySelectorAll('[data-tilt]').forEach(card=>{card.addEventListener('pointermove',event=>{if(reduced||event.pointerType==='touch')return;const rect=card.getBoundingClientRect(),x=(event.clientX-rect.left)/rect.width,y=(event.clientY-rect.top)/rect.height;card.style.setProperty('--tilt-x',(x-.5)*7+'deg');card.style.setProperty('--tilt-y',(y-.5)*-7+'deg');card.style.setProperty('--card-x',x*100+'%');card.style.setProperty('--card-y',y*100+'%');});card.addEventListener('pointerleave',()=>{card.style.setProperty('--tilt-x','0deg');card.style.setProperty('--tilt-y','0deg');});});
const methodAreas=[{number:'01 / TECNOLOGÍA & CUIDADO',title:'Aparatología.',description:'La tecnología como parte de un plan de cuidado individual. Conoce con el equipo qué equipos y procedimientos están disponibles y cuáles corresponden a tu valoración.'},{number:'02 / MEDICINA ESTÉTICA',title:'Cuidar tu expresión.',description:'La clínica comparte protocolos personalizados de piel, Fullface Regenerativo, Botox e HydraFacial. Consulta sus indicaciones y opciones con el equipo médico.'},{number:'03 / FUNCIONAL & REGENERATIVA',title:'Una mirada integral.',description:'Un área que forma parte de The Insiders Method y conecta la conversación sobre salud, bienestar y longevidad. Explora con la clínica su enfoque y los programas Origen y Origen Gastro.'},{number:'04 / FARMACIA',title:'Continuidad del cuidado.',description:'La farmacia forma parte del método presentado por Insiders. Consulta directamente con el equipo los productos disponibles y su uso indicado; los medicamentos requieren la orientación y receta que corresponda.'}];
let activeMethod=0;
document.querySelectorAll('[data-method]').forEach((button,index)=>button.addEventListener('click',()=>{activeMethod=index;document.querySelectorAll('[data-method]').forEach(item=>{item.classList.toggle('active',item===button);item.setAttribute('aria-pressed',String(item===button));});const data=methodAreas[index];$('#method-number').textContent=data.number;$('#method-title').textContent=data.title;$('#method-description').textContent=data.description;$('.method-detail-art').style.filter='hue-rotate('+index*15+'deg)';}));
$('#method-consult')?.addEventListener('click',()=>openContact(methodAreas[activeMethod].title.replace('.','')));
const stages=[{number:'01 / EL PRIMER ENCUENTRO',title:'Todo empieza contigo.',description:'Comparte lo que buscas, cómo te sientes y las preguntas que te gustaría resolver. Tu historia es el punto de partida.'},{number:'02 / UNA MIRADA PERSONAL',title:'Entender tu punto de partida.',description:'Conversa con el equipo sobre tu historia y tus prioridades. La valoración profesional permite conocer qué opciones podrían corresponder a tus necesidades.'},{number:'03 / TU PROPIO RECORRIDO',title:'Un plan alrededor de ti.',description:'Explora una propuesta que conecte las áreas de Insiders con tus objetivos. Los procedimientos, alcances y tiempos se definen directamente con el equipo médico.'},{number:'04 / DISFRUTA EL VIAJE',title:'Acompañar tu evolución.',description:'Da seguimiento con la clínica a tus preguntas y a tu experiencia. Tu cuidado es una conversación que continúa a lo largo del viaje.'}];
document.querySelectorAll('[data-step]').forEach((button,index)=>button.addEventListener('click',()=>{document.querySelectorAll('[data-step]').forEach(item=>{item.classList.toggle('active',item===button);item.setAttribute('aria-pressed',String(item===button));});const data=stages[index];$('#stage-number').textContent=data.number;$('#stage-title').textContent=data.title;$('#stage-description').textContent=data.description;$('.stage-art').style.setProperty('--stage-scale',1+index*.05);$('.stage-art').style.filter='hue-rotate('+index*3+'deg)';}));
function setup(canvas,environment=false){const scene=new THREE.Scene(),renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.88;const camera=new THREE.PerspectiveCamera(36,1,.1,100);scene.add(new THREE.HemisphereLight(0xffffff,0x77858b,1.0));const key=new THREE.DirectionalLight(0xffffff,2.1);key.position.set(-3,5,6);scene.add(key);const rim=new THREE.DirectionalLight(page==='journey'?0xff798e:0xb5f4f1,2);rim.position.set(4,1,-4);scene.add(rim);if(environment){const generator=new THREE.PMREMGenerator(renderer),room=new RoomEnvironment();scene.environment=generator.fromScene(room,.04).texture;room.dispose();generator.dispose();}const controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.enablePan=false;const size=()=>{const rect=canvas.parentElement.getBoundingClientRect();if(!rect.width||!rect.height)return;renderer.setSize(rect.width,rect.height,false);camera.aspect=rect.width/rect.height;camera.updateProjectionMatrix();};new ResizeObserver(size).observe(canvas.parentElement);size();return {scene,renderer,camera,controls,size};}
let skinState;
try{
const s=setup($('#skin-scene'),true);skinState=s;s.camera.position.set(0,0,9.7);s.controls.enableZoom=false;s.controls.rotateSpeed=.45;s.controls.autoRotate=false;
const colors={home:[0xbfdcdd,0xf2f7f7,0x789397],healthcare:[0x93a8aa,0xf6fafb,0x3f565b],core:[0x6d8da1,0xd4e5ed,0x324d60],uniqueness:[0x5dd8d0,0xb2fff7,0x217b87],journey:[0xef6179,0xffb8c4,0x9c143b]}[page];
const group=new THREE.Group();s.scene.add(group);group.rotation.z=-.23;
const membraneMat=new THREE.MeshPhysicalMaterial({color:colors[0],metalness:.14,roughness:.12,transmission:.48,thickness:1.1,ior:1.32,clearcoat:1,clearcoatRoughness:.05,envMapIntensity:1.2});
const nucleusMat=new THREE.MeshPhysicalMaterial({color:colors[2],metalness:.35,roughness:.2,clearcoat:1,envMapIntensity:1.25});
const dropMat=new THREE.MeshPhysicalMaterial({color:colors[1],metalness:.04,roughness:.07,transmission:.72,thickness:.7,ior:1.4,clearcoat:1});
const shaders=[];
function livingMaterial(material){material.onBeforeCompile=shader=>{shader.uniforms.uTime={value:0};shader.vertexShader='uniform float uTime;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\n float wave = sin(position.x*2.8+uTime)*sin(position.y*2.0-uTime*.7)*sin(position.z*2.5+uTime*.4);\n transformed += normal * wave * .07;');shaders.push(shader);};return material;}
livingMaterial(membraneMat);
const membraneGeometry=new THREE.SphereGeometry(1.52,64,48);const position=membraneGeometry.attributes.position;
for(let i=0;i<position.count;i++){const x=position.getX(i),y=position.getY(i),z=position.getZ(i),deform=1+.05*Math.sin(x*2.4+y)*Math.cos(z*2.5);position.setXYZ(i,x*deform,y*deform*1.06,z*deform);}
membraneGeometry.computeVertexNormals();const membrane=new THREE.Mesh(membraneGeometry,membraneMat);group.add(membrane);
const nucleus=new THREE.Mesh(new THREE.SphereGeometry(.79,48,32),nucleusMat);nucleus.position.set(.13,-.1,-.15);group.add(nucleus);
// Gentle folds evoke the membrane and skin-care textures in the brand references.
const foldMat=new THREE.MeshPhysicalMaterial({color:colors[1],metalness:.45,roughness:.19,transparent:true,opacity:.78,clearcoat:1});
for(let i=0;i<3;i++){const fold=new THREE.Mesh(new THREE.TorusGeometry(1.39-i*.12,.045+i*.012,12,110,Math.PI*1.58),foldMat);fold.rotation.set(.85+i*.3,.3+i*.35,.6+i*.55);group.add(fold);}
const droplets=[];const points=[[-1.8,1.35,.4,.39],[1.72,.73,.2,.48],[-1.45,-1.57,.5,.52],[1.45,-1.45,-.1,.29],[-.7,1.95,-.4,.19],[2.05,-.35,.5,.16]];
points.forEach(([x,y,z,r],index)=>{const droplet=new THREE.Mesh(new THREE.SphereGeometry(r,32,24),index%2?dropMat:membraneMat);droplet.position.set(x,y,z);group.add(droplet);droplets.push({mesh:droplet,y,phase:index*1.3});});
// Small inclusions within the central form are artistic, not anatomical.
const particleMat=new THREE.MeshStandardMaterial({color:colors[1],roughness:.25,metalness:.2});
for(let i=0;i<26;i++){const angle=i*2.399,r=.48+.23*Math.sin(i);const particle=new THREE.Mesh(new THREE.SphereGeometry(.025+(i%3)*.008,10,8),particleMat);particle.position.set(Math.cos(angle)*r,Math.sin(angle)*r,(i%9-4)*.1);group.add(particle);}
// Each universe has its own sculpture and spatial language.
if(page!=='healthcare'){
while(group.children.length)group.remove(group.children[0]);droplets.length=0;
const add=(geometry,material,x=0,y=0,z=0)=>{const mesh=new THREE.Mesh(geometry,material);mesh.position.set(x,y,z);group.add(mesh);return mesh;};
if(page==='home'){
const globeMat=new THREE.MeshPhysicalMaterial({color:0x234d5d,metalness:.48,roughness:.28,clearcoat:1});
add(new THREE.SphereGeometry(1.65,80,64),globeMat);
const landMat=new THREE.MeshStandardMaterial({color:0xb7d4cb,metalness:.2,roughness:.55});
const continents=[ [[-168,70],[-140,72],[-125,60],[-112,52],[-85,50],[-60,58],[-53,45],[-80,25],[-88,20],[-100,15],[-110,28],[-125,40],[-135,56]], [[-81,12],[-68,10],[-50,2],[-35,-9],[-45,-25],[-57,-40],[-69,-55],[-76,-35],[-80,-8]], [[-17,35],[10,37],[35,30],[43,12],[51,9],[40,-10],[30,-35],[17,-35],[8,-8],[-10,5]], [[-10,36],[-10,58],[15,70],[50,72],[80,75],[115,70],[150,60],[180,66],[180,48],[140,35],[120,20],[105,0],[95,18],[78,7],[66,25],[45,30],[35,40],[20,35]], [[112,-11],[136,-12],[153,-25],[145,-39],[115,-35]], [[-55,60],[-25,72],[-32,82],[-60,82]], [[47,-14],[50,-26],[44,-24]] ];
function geo(lon,lat,r){const a=lon*Math.PI/180,b=lat*Math.PI/180;return new THREE.Vector3(r*Math.cos(b)*Math.sin(a),r*Math.sin(b),r*Math.cos(b)*Math.cos(a));}
function inside(x,y,poly){let yes=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const [a,b]=poly[i],[c,d]=poly[j];if(((b>y)!==(d>y))&&x<(c-a)*(y-b)/(d-b)+a)yes=!yes;}return yes;}
const landPoints=[];for(let lon=-180;lon<180;lon+=2.5)for(let lat=-57;lat<83;lat+=2.5)if(continents.some(poly=>inside(lon,lat,poly)))landPoints.push(geo(lon,lat,1.664));
const dots=new THREE.InstancedMesh(new THREE.SphereGeometry(.025,6,5),landMat,landPoints.length),matrix=new THREE.Matrix4();landPoints.forEach((point,i)=>{matrix.makeTranslation(point.x,point.y,point.z);dots.setMatrixAt(i,matrix);});group.add(dots);
const lineMat=new THREE.LineBasicMaterial({color:0x86bcb9,transparent:true,opacity:.25});
for(let lat=-60;lat<=60;lat+=30){const pts=[];for(let lon=0;lon<=360;lon+=3)pts.push(geo(lon,lat,1.67));group.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),lineMat));}
for(let lon=0;lon<180;lon+=30){const ring=add(new THREE.TorusGeometry(1.67,.004,4,100),new THREE.MeshBasicMaterial({color:0x8fbcba,transparent:true,opacity:.22}));ring.rotation.y=lon*Math.PI/180;}
const places=[[-103,21],[2,49],[139,36],[77,28],[151,-33]];
for(let k=1;k<places.length;k++){const a=geo(...places[0],1.7),b=geo(...places[k],1.7),mid=a.clone().add(b).normalize().multiplyScalar(2.5);const curve=new THREE.QuadraticBezierCurve3(a,mid,b);add(new THREE.TubeGeometry(curve,60,.012,6,false),new THREE.MeshBasicMaterial({color:0xcde8dd}));const point=geo(...places[k],1.72);add(new THREE.SphereGeometry(.065,16,12),new THREE.MeshBasicMaterial({color:0xffffff}),point.x,point.y,point.z);}
group.rotation.y=-.5;group.rotation.z=.1;
}else if(page==='core'){
for(const [x,y,z,r] of [[0,0,0,1.12],[-1.35,.7,.15,.82],[1.25,.95,-.3,.92],[.8,-1.2,.2,.75],[-.7,-1.15,-.2,.64]])add(new THREE.SphereGeometry(r,48,32),nucleusMat,x,y,z);
}else if(page==='uniqueness'){
const ribbon=add(new THREE.TorusKnotGeometry(1.15,.23,180,30,2,3),new THREE.MeshPhysicalMaterial({color:0x5ee1d4,metalness:.65,roughness:.18,clearcoat:1}));ribbon.rotation.x=.7;ribbon.rotation.y=.5;
}else if(page==='journey'){
add(new THREE.SphereGeometry(1.1,64,48),new THREE.MeshPhysicalMaterial({color:0xbd1636,emissive:0x74081a,emissiveIntensity:.35,metalness:.35,roughness:.3,clearcoat:1}));
for(let i=0;i<5;i++){const ring=add(new THREE.TorusGeometry(1.35+i*.19,.035,12,140),new THREE.MeshPhysicalMaterial({color:0xf88191,metalness:.5,roughness:.24,transparent:true,opacity:.7-i*.08}));ring.rotation.x=.55+i*.12;ring.rotation.y=.35;}
}
}
let visible=true,dragging=false,lastTime=0,animationTime=0;
new IntersectionObserver(([entry])=>visible=entry.isIntersecting).observe($('#skin-scene'));
$('#skin-scene').addEventListener('pointerdown',()=>dragging=true);window.addEventListener('pointerup',()=>dragging=false);
const pause=$('#scene-pause');function syncPause(){pause.textContent=motionPaused?'▷':'Ⅱ';pause.setAttribute('aria-label',motionPaused?'Reanudar animación':'Pausar animación');pause.setAttribute('aria-pressed',String(motionPaused));}
pause.addEventListener('click',()=>{motionPaused=!motionPaused;syncPause();});syncPause();
reducedQuery.addEventListener('change',event=>{reduced=event.matches;motionPaused=reduced;syncPause();});
s.renderer.setAnimationLoop(time=>{const delta=Math.min((time-lastTime)/1000,.05);lastTime=time;if(!visible||document.hidden)return;if(!motionPaused){animationTime+=delta;shaders.forEach(shader=>shader.uniforms.uTime.value=animationTime*.45);group.position.y=Math.sin(animationTime*.45)*.07;droplets.forEach(d=>d.mesh.position.y=d.y+Math.sin(animationTime*.6+d.phase)*.06);if(!dragging){const targetX=pointer.y*.09,targetY=pointer.x*.16+(page==='home'?animationTime*.08:Math.sin(animationTime*.15)*.07);group.rotation.x+=(targetX-group.rotation.x)*.025;group.rotation.y+=(targetY-group.rotation.y)*.025;}}s.controls.update();s.renderer.render(s.scene,s.camera);});
}catch(error){console.error('No fue posible iniciar la escena WebGL.',error);$('.scene-fallback').hidden=false;$('#scene-pause').hidden=true;$('.scene-controls>span').textContent='Interpretación visual de bienestar';}
let roomState;function makeRoom(){const s=setup($('#room'));s.renderer.toneMappingExposure=.92;s.scene.background=new THREE.Color(0xe2e7eb);s.camera.position.set(9,8,11);s.controls.target.set(0,.7,0);s.controls.minDistance=6;s.controls.maxDistance=20;s.controls.maxPolarAngle=Math.PI*.48;const model=new THREE.Group();s.scene.add(model);const mat=(c,r=.65,m=0)=>new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:m});const stone=mat(0xd3dcdf),wall=mat(0xf1f4f5),wood=mat(0x687b85),fabric=mat(0xafc3cc),gold=mat(0xabb8c0,.3,.65),green=mat(0x607c73);function box(w,h,d,x,y,z,m){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);o.position.set(x,y,z);model.add(o);return o;}function sphere(r,x,y,z,m,sy=1){const o=new THREE.Mesh(new THREE.SphereGeometry(r,24,16),m);o.position.set(x,y,z);o.scale.y=sy;model.add(o);return o;}function cylinder(r1,r2,h,x,y,z,m){const o=new THREE.Mesh(new THREE.CylinderGeometry(r1,r2,h,32),m);o.position.set(x,y,z);model.add(o);return o;}
box(10,.3,7,0,-.15,0,stone);box(10,3,.15,0,1.5,-3.5,wall);box(.15,3,7,-5,1.5,0,wall);box(.12,2.7,3.9,1.6,1.35,-1.45,wall);for(let i=0;i<21;i++)box(.045,2.5,.05,-4.7+i*.17,1.5,-3.38,wood);box(2.7,1.15,.9,-2.65,.575,-1.7,stone);box(2.85,.07,1,-2.65,1.18,-1.7,wood);box(1.2,.015,.4,-2.65,1.23,-1.7,gold);box(.65,.035,.4,-3.3,1.25,-1.7,mat(0x23373d));box(.03,.5,.03,-3.3,1.5,-1.75,gold);const screen=box(.65,.4,.035,-3.3,1.65,-1.75,mat(0x23373d));screen.rotation.x=-.12;
// Treatment bed with segmented cushions, supports and headrest.
box(1.4,.22,2.3,3,.9,-1.7,fabric);box(1.48,.12,2.35,3,.73,-1.7,wall);box(.85,.55,1.2,3,.4,-1.7,stone);box(1.1,.08,1.7,3,.13,-1.7,gold);box(1.1,.14,.5,3,1.08,-2.45,wall);for(const z of [-2.9,-2.5,-2.1,-1.7,-1.3,-.9])box(1.36,.014,.015,3,1.018,z,stone);
// Waiting area upholstered lounge chairs and table.
for(const x of [-3.4,-1.8]){box(1.15,.22,1.1,x,.5,1.6,fabric);box(1.15,.85,.22,x,.95,2.08,fabric);for(const a of [-.48,.48]){box(.13,.65,1.12,x+a,.7,1.6,wood);box(.08,.4,.08,x+a,.2,1.2,gold);box(.08,.4,.08,x+a,.2,2,gold);}}cylinder(.6,.6,.1,-2.6,.58,.1,stone);cylinder(.075,.075,.5,-2.6,.28,.1,gold);cylinder(.36,.36,.06,-2.6,.04,.1,gold);cylinder(.09,.09,.2,-2.6,.73,.1,wall);sphere(.12,-2.6,.9,.1,green,.6);
// Planters, branching trunks and leaf clusters.
for(const [x,z]of [[-4.4,-2.7],[4.1,2.4]]){cylinder(.33,.24,.7,x,.35,z,stone);cylinder(.04,.08,1.8,x,1.4,z,wood);for(let i=0;i<25;i++){const a=i*2.4,r=.25+(i%4)*.1;const leaf=sphere(.2,x+Math.cos(a)*r,1.7+(i%7)*.12,z+Math.sin(a)*r,green,.55);leaf.rotation.z=a;}}for(let i=0;i<5;i++){box(.7,.035,.15,2.3+i*.43,2.4,-3.35,gold);}const ring=new THREE.Mesh(new THREE.TorusGeometry(.58,.035,16,64),gold);ring.position.set(-.6,1.9,-3.37);model.add(ring);
// Sculptural clinical lamp, storage, shelves and bottles.
cylinder(.04,.04,1.9,4.2,1,-2.8,gold);cylinder(.32,.32,.07,4.2,.06,-2.8,gold);sphere(.25,4.2,2,-2.8,wall,.4);box(.9,1,.45,4.4,.5,-.3,wall);for(let i=0;i<3;i++)box(.8,.02,.02,4.4,.25+i*.3,-.06,gold);for(let i=0;i<4;i++){box(1,.05,.45,-4.4,1.2+i*.38,-.8,wood);for(let j=0;j<3;j++)cylinder(.045,.045,.17,-4.65+j*.22,1.31+i*.38,-.8,wall);}const light=new THREE.PointLight(0xe6f8ff,8,12);light.position.set(0,4,0);s.scene.add(light);s.renderer.setAnimationLoop(()=>{if($('#room-dialog').open&&!document.hidden){s.controls.update();s.renderer.render(s.scene,s.camera);}});let night=false;$('#room-day').onclick=()=>{night=!night;s.scene.background.set(night?0x17262e:0xe2e7eb);s.renderer.toneMappingExposure=night?.55:.92;$('#room-day').textContent=night?'Ambiente de día':'Ambiente de noche';};$('#room-reset').onclick=()=>{s.camera.position.set(9,8,11);s.controls.target.set(0,.7,0);s.controls.update();};return s;}

document.querySelectorAll('[data-open-room]').forEach(button=>button.addEventListener('click',()=>{$('#room-dialog').showModal();try{roomState??=makeRoom();roomState.size();}catch(error){console.error(error);$('.room-wrap').textContent='El modelo 3D necesita un navegador con WebGL habilitado.';}}));
if(!reduced){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target);}}),{threshold:.12});document.querySelectorAll('.intro-section h2,.section-heading,.team-section>div:last-child,.reference-section>div:last-child,.core-statement>h2,.unique-statement>h2,.journey-intro>h2,.journey-end>h2').forEach(element=>{element.classList.add('reveal');observer.observe(element);});}
