import * as THREE from 'three';
import { OrbitControls } from './assets/OrbitControls.js';
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const $=s=>document.querySelector(s);
const contact=$('#contact-modal');
function showContact(subject=''){ $('#whatsapp').href='https://wa.me/523319045014?text='+encodeURIComponent('Hola Insiders, me gustaría conocer sus servicios y consultar una valoración'+(subject?' sobre '+subject:'')+'.');contact.showModal(); }
document.querySelectorAll('[data-contact]').forEach(b=>b.addEventListener('click',()=>showContact()));
document.querySelectorAll('dialog').forEach(d=>{d.querySelector('.close').addEventListener('click',()=>d.close());d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});});
$('#sources').onclick=()=>$('#sources-modal').showModal();
$('#menu').onclick=()=>{$('nav').classList.toggle('open');$('#menu').setAttribute('aria-expanded',$('nav').classList.contains('open'));};document.querySelectorAll('nav a').forEach(a=>a.onclick=()=>{$('nav').classList.remove('open');$('#menu').setAttribute('aria-expanded','false');});
const areas=[['01 — ESTÉTICA','La belleza de<br>ser tú.','Una conversación sobre tu piel, tu expresión y lo que buscas. El primer paso es una valoración individual con el equipo de la clínica.',['Protocolos personalizados de piel','Fullface Regenerativo e HydraFacial','Valoración profesional'],'AESTHETICS'],['02 — LONGEVIDAD','Disfruta el viaje.<br>Piensa a futuro.','La clínica presenta el Programa Origen como una evaluación integral para conocer tu estado de salud y construir una estrategia personalizada.',['Programa Origen','Estrategia individual de salud','Valoración con el equipo'],'LONGEVITY'],['03 — BIENESTAR','Sentirte bien.<br>Desde adentro.','Insiders comparte el Programa Origen Gastro y un enfoque de bienestar basado en personalización y equilibrio. Consulta con el equipo cómo comenzar.',['Programa Origen Gastro','Bienestar digestivo','Personalización y equilibrio'],'WELLNESS']];
document.querySelectorAll('[data-tab]').forEach((b,i)=>{b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(t=>t.setAttribute('aria-selected',String(t===b)));const a=areas[i];$('#panel-kicker').textContent=a[0];$('#panel-title').innerHTML=a[1];$('#panel-desc').textContent=a[2];$('#panel-list').replaceChildren(...a[3].map(t=>{const l=document.createElement('li');l.textContent=t;return l;}));$('#orb-word').textContent=a[4];$('.orb-art').style.filter=`hue-rotate(${i*22}deg)`;};b.onkeydown=e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const tabs=[...document.querySelectorAll('[data-tab]')],next=tabs[(i+(e.key==='ArrowRight'?1:2))%3];next.focus();next.click();}};});
let selected='';document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{selected=b.dataset.choice;document.querySelectorAll('[data-choice]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b));});$('.journey-result').hidden=false;$('#result-title').textContent=selected+' puede ser el comienzo.';});$('#journey-contact').onclick=()=>showContact(selected);
function setup(canvas){const scene=new THREE.Scene();const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;const camera=new THREE.PerspectiveCamera(36,1,.1,100);scene.add(new THREE.HemisphereLight(0xffffff,0x6d745b,3));const key=new THREE.DirectionalLight(0xffffff,5);key.position.set(-4,6,5);scene.add(key);const fill=new THREE.DirectionalLight(0xd6e5b3,3);fill.position.set(5,-1,-4);scene.add(fill);const controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.enablePan=false;const size=()=>{const rect=canvas.parentElement.getBoundingClientRect();if(!rect.width||!rect.height)return;renderer.setSize(rect.width,rect.height,false);camera.aspect=rect.width/rect.height;camera.updateProjectionMatrix();};new ResizeObserver(size).observe(canvas.parentElement);size();return {scene,renderer,camera,controls,size};}
let paused=reduced;
try{const s=setup($('#molecule'));s.camera.position.set(0,.2,9);s.controls.enableZoom=false;s.controls.autoRotate=!paused;s.controls.autoRotateSpeed=.7;const cluster=new THREE.Group();s.scene.add(cluster);const silver=new THREE.MeshPhysicalMaterial({color:0xa4ae8d,metalness:.55,roughness:.18,clearcoat:1});const pearl=new THREE.MeshPhysicalMaterial({color:0xe7ecdc,metalness:.18,roughness:.16,clearcoat:1});const dark=new THREE.MeshPhysicalMaterial({color:0x6f795c,metalness:.65,roughness:.23});const points=[[-1.2,1.5,.1],[.25,1.65,-.55],[1.45,.65,.3],[1.25,-.8,-.4],[-.2,-1.6,.2],[-1.6,-.65,-.5],[-1.8,.5,.65],[0,.1,.1],[.45,-.2,1.1]];points.forEach((p,i)=>{const ball=new THREE.Mesh(new THREE.SphereGeometry(i===7?.85:.52+(i%3)*.1,64,48),[silver,pearl,dark][i%3]);ball.position.set(...p);cluster.add(ball);});const edges=[[0,1],[1,2],[2,3],[3,4],[4,5],[5,6],[6,0],[0,7],[2,7],[4,7],[6,7],[7,8],[3,8]];edges.forEach(([i,j])=>{const a=new THREE.Vector3(...points[i]),b=new THREE.Vector3(...points[j]),v=b.clone().sub(a);const m=new THREE.Mesh(new THREE.CylinderGeometry(.13,.13,v.length(),24),silver);m.position.copy(a).add(b).multiplyScalar(.5);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),v.normalize());cluster.add(m);});cluster.rotation.z=.2;const dust=new THREE.BufferGeometry();const positions=[];for(let i=0;i<70;i++){const a=i*2.399;positions.push(Math.cos(a)*(3+i%5*.15),Math.sin(a)*(2.3+i%7*.07),(i%9-4)*.3);}dust.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));s.scene.add(new THREE.Points(dust,new THREE.PointsMaterial({color:0x87966f,size:.025,transparent:true,opacity:.5})));$('#pause').textContent=paused?'▷':'Ⅱ';$('#pause').onclick=()=>{paused=!paused;s.controls.autoRotate=!paused;$('#pause').textContent=paused?'▷':'Ⅱ';$('#pause').setAttribute('aria-label',paused?'Reanudar animación 3D':'Pausar animación 3D');};let visible=true;new IntersectionObserver(([e])=>visible=e.isIntersecting).observe($('#molecule'));s.renderer.setAnimationLoop(t=>{if(!visible||document.hidden)return;s.controls.update();if(!paused)cluster.position.y=Math.sin(t*.0005)*.08;s.renderer.render(s.scene,s.camera);});}catch(e){console.error('3D no disponible',e);$('.scene-fallback').hidden=false;$('#pause').hidden=true;$('.visual-controls span').textContent='Vista conceptual';}
let roomState;function makeRoom(){const s=setup($('#room'));s.renderer.toneMappingExposure=.92;s.scene.background=new THREE.Color(0xe6eadd);s.camera.position.set(9,8,11);s.controls.target.set(0,.7,0);s.controls.minDistance=6;s.controls.maxDistance=20;s.controls.maxPolarAngle=Math.PI*.48;const model=new THREE.Group();s.scene.add(model);const mat=(c,r=.65,m=0)=>new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:m});const stone=mat(0xe7dfcf),wall=mat(0xf7f0e3),wood=mat(0x9e8867),fabric=mat(0xc4c8b4),gold=mat(0xbba779,.3,.65),green=mat(0x6d7b57);function box(w,h,d,x,y,z,m){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);o.position.set(x,y,z);model.add(o);return o;}function sphere(r,x,y,z,m,sy=1){const o=new THREE.Mesh(new THREE.SphereGeometry(r,24,16),m);o.position.set(x,y,z);o.scale.y=sy;model.add(o);return o;}function cylinder(r1,r2,h,x,y,z,m){const o=new THREE.Mesh(new THREE.CylinderGeometry(r1,r2,h,32),m);o.position.set(x,y,z);model.add(o);return o;}
box(10,.3,7,0,-.15,0,stone);box(10,3,.15,0,1.5,-3.5,wall);box(.15,3,7,-5,1.5,0,wall);box(.12,2.7,3.9,1.6,1.35,-1.45,wall);for(let i=0;i<21;i++)box(.045,2.5,.05,-4.7+i*.17,1.5,-3.38,wood);box(2.7,1.15,.9,-2.65,.575,-1.7,stone);box(2.85,.07,1,-2.65,1.18,-1.7,wood);box(1.2,.015,.4,-2.65,1.23,-1.7,gold);box(.65,.035,.4,-3.3,1.25,-1.7,mat(0x484d41));box(.03,.5,.03,-3.3,1.5,-1.75,gold);const screen=box(.65,.4,.035,-3.3,1.65,-1.75,mat(0x404c3c));screen.rotation.x=-.12;
// Treatment bed with segmented cushions, supports and headrest.
box(1.4,.22,2.3,3,.9,-1.7,fabric);box(1.48,.12,2.35,3,.73,-1.7,wall);box(.85,.55,1.2,3,.4,-1.7,stone);box(1.1,.08,1.7,3,.13,-1.7,gold);box(1.1,.14,.5,3,1.08,-2.45,wall);for(const z of [-2.9,-2.5,-2.1,-1.7,-1.3,-.9])box(1.36,.014,.015,3,1.018,z,stone);
// Waiting area upholstered lounge chairs and table.
for(const x of [-3.4,-1.8]){box(1.15,.22,1.1,x,.5,1.6,fabric);box(1.15,.85,.22,x,.95,2.08,fabric);for(const a of [-.48,.48]){box(.13,.65,1.12,x+a,.7,1.6,wood);box(.08,.4,.08,x+a,.2,1.2,gold);box(.08,.4,.08,x+a,.2,2,gold);}}cylinder(.6,.6,.1,-2.6,.58,.1,stone);cylinder(.075,.075,.5,-2.6,.28,.1,gold);cylinder(.36,.36,.06,-2.6,.04,.1,gold);cylinder(.09,.09,.2,-2.6,.73,.1,wall);sphere(.12,-2.6,.9,.1,green,.6);
// Planters, branching trunks and leaf clusters.
for(const [x,z]of [[-4.4,-2.7],[4.1,2.4]]){cylinder(.33,.24,.7,x,.35,z,stone);cylinder(.04,.08,1.8,x,1.4,z,wood);for(let i=0;i<25;i++){const a=i*2.4,r=.25+(i%4)*.1;const leaf=sphere(.2,x+Math.cos(a)*r,1.7+(i%7)*.12,z+Math.sin(a)*r,green,.55);leaf.rotation.z=a;}}for(let i=0;i<5;i++){box(.7,.035,.15,2.3+i*.43,2.4,-3.35,gold);}const ring=new THREE.Mesh(new THREE.TorusGeometry(.58,.035,16,64),gold);ring.position.set(-.6,1.9,-3.37);model.add(ring);
// Sculptural clinical lamp, storage, shelves and bottles.
cylinder(.04,.04,1.9,4.2,1,-2.8,gold);cylinder(.32,.32,.07,4.2,.06,-2.8,gold);sphere(.25,4.2,2,-2.8,wall,.4);box(.9,1,.45,4.4,.5,-.3,wall);for(let i=0;i<3;i++)box(.8,.02,.02,4.4,.25+i*.3,-.06,gold);for(let i=0;i<4;i++){box(1,.05,.45,-4.4,1.2+i*.38,-.8,wood);for(let j=0;j<3;j++)cylinder(.045,.045,.17,-4.65+j*.22,1.31+i*.38,-.8,wall);}const light=new THREE.PointLight(0xffecd1,8,12);light.position.set(0,4,0);s.scene.add(light);s.renderer.setAnimationLoop(()=>{if($('#room-modal').open&&!document.hidden){s.controls.update();s.renderer.render(s.scene,s.camera);}});let night=false;$('#room-day').onclick=()=>{night=!night;s.scene.background.set(night?0x353d32:0xe6eadd);s.renderer.toneMappingExposure=night?.55:.92;$('#room-day').textContent=night?'Ambiente de día':'Ambiente de noche';};$('#room-reset').onclick=()=>{s.camera.position.set(9,8,11);s.controls.target.set(0,.7,0);s.controls.update();};return s;}
$('#open-room').onclick=()=>{$('#room-modal').showModal();try{roomState??=makeRoom();roomState.size();}catch(e){console.error(e);$('.room-wrap').textContent='El modelo 3D necesita un navegador con WebGL habilitado.';}};

if(!reduced){const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('revealed');observer.unobserve(e.target);}}),{threshold:.12});document.querySelectorAll('.section-head,.philosophy>div,.steps article,.program-card,.closing h2').forEach(el=>{el.classList.add('reveal');observer.observe(el);});}
